// "use client"
import localFont from "next/font/local";
import "./globals.css";
// import { Elements } from '@stripe/react-stripe-js';
// import { loadStripe } from '@stripe/stripe-js';
// const stripePromise = loadStripe(process.env.STRIPE_PUBLIC_KEY)

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const metadata = {
  title: "SAAS Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <Elements stripe={stripePromise}>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
    // </Elements>
  );
}
